spring.application.name=elective

# MySQL база даних
spring.datasource.url=jdbc:mysql://localhost:3306/electivedb?serverTimezone=UTC&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=S102047m

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Actuator (профілювання)
management.endpoints.web.exposure.include=health,info,metrics,beans,env
management.endpoint.health.show-details=always

server.port=8080